{% set version = '1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-didforbigdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DiDforBigData_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DiDforBigData/DiDforBigData_{{ version }}.tar.gz
  sha256: 21e164520b1a58b70cb323e201aaf6e3f6bb9521c2113b94a457bf2c4fe62039

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-data.table
    - r-sandwich
  run:
    - r-base
    - r-data.table
    - r-sandwich

test:
  commands:
    - $R -e "library('DiDforBigData')"           # [not win]
    - "\"%R%\" -e \"library('DiDforBigData')\""  # [win]

about:
  home: https://setzler.github.io/DiDforBigData/
  license: MIT
  summary: Provides a big-data-friendly and memory-efficient difference-in-differences estimator
    for staggered (and non-staggered) treatment contexts.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec

# Package: DiDforBigData
# Title: A Big Data Implementation of Difference-in-Differences Estimation with Staggered Treatment
# Version: 1.0
# Authors@R: person("Bradley", "Setzler", , "bradley.setzler@gmail.com", role = c("aut", "cre", "cph"))
# Description: Provides a big-data-friendly and memory-efficient difference-in-differences estimator for staggered (and non-staggered) treatment contexts.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Depends: data.table, sandwich
# Suggests: ggplot2, knitr, rmarkdown, scales, parallel, fixest, progress
# VignetteBuilder: knitr
# URL: https://setzler.github.io/DiDforBigData/
# BugReports: https://github.com/setzler/DiDforBigData/issues
# NeedsCompilation: no
# Packaged: 2023-04-02 23:58:12 UTC; bradleysetzler
# Author: Bradley Setzler [aut, cre, cph]
# Maintainer: Bradley Setzler <bradley.setzler@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-04-03 15:50:02 UTC
